### ISSUE TITLE
안녕하세요

### ISSUE THREAD

**Issue by Taeyeon1607** [EZYOON/ezyoon.github.io#1]
안녕하세요 kobert에 남긴 이슈 리포트보고 연락드립니다.

먼저, github 사용법을 잘 몰라 이렇게 issue란에 남기는 점 죄송합니다.

혹시 불편을 드렸다면 삭제하겠습니다.

다름이 아니라 kobert를 설치하시는 과정에서 numpy dependency 에러를 겪었는데

유일하게 단서를 찾은 것이라 여쭙고자 연락드렸습니다(저도 windows10 환경입니다).

report해주신 것과 동일한 numpy dependency error를 저도 겪고 있는데 

도저히 해결이 안 되어 말씀해주신 onnxruntime 0.5.0 버전을 설치해보려고 하는데

잘 안되네요.

pip로는 안먹히고(너무 예전 버전이라 그런지..),

따로 whl(gpu 버전) 파일 어떻게 구해서 pip install로 해봐도 잘 안되네요

혹시 다른 해결방법이나 whl 파일을 공유해주실 수 있으신가요?ㅠㅠ

boto3 - 1.15.18
gluonnlp - 0.10.0
mxnet - 1.7.0.post2
onnxruntime - 0.5.0
sentencepiece - 0.1.96
torch - 1.10.1
transformers - 3.0.2

위 모듈들 중 onnxruntime만 버전을 못 맞추고 있고,

kobert 설치과정에서 계속 numpy 의존성 문제가 발생하는걸로 봐서는

onnxruntime 버전만 맞춰주면 될 것 같은데 정말 어렵네요.

번거로우시겠지만 혹시 도움주실 수 있으시다면 감사하겠습니다!

**Comment by EZYOON** [comment]
https://mirrors.huaweicloud.com/repository/pypi/simple/onnxruntime-gpu/

**Comment by EZYOON** [comment]
저는 window 환경이 아니기 때문에 환경이 동일하지는 않아요.
시도해본 방법은

1. pip install onnxruntime 로 최신 버전 설치
2. whl 파일을 다운받아 설치
* https://pypi.org/simple/onnxruntime/
* https://mirrors.huaweicloud.com/repository/pypi/simple/onnxruntime-gpu/
* 파이썬버전과 운영체제 맞는 whl 파일을 다운

저는 2번으로 시도하다가 kobert github에 이슈를 올린 이후 onnx 1.8.0 버전으로 업데이트를 하셨다는 답변을 듣고 최신버전으로 다운로드하여 해결되었어요.
0.5.0 버전은 다른 분의 사례라 제게 도움드리지는 못할 것 같아요.. 🥲

**Comment by Taeyeon1607** [comment]
그렇군요. 알려주셔서 정말 감사합니다.

알려주신 방법으로 시도해볼게요^^

번거로우실텐데 도움주셔서 정말 감사합니다.

좋은 하루 되세요!

2022년 2월 9일 (수) 오후 1:50, EZYOON ***@***.***>님이 작성:
